GH action fixes

diff --git a/.github/workflows/pre-deploy.yml b/.github/workflows/pre-deploy.yml
--- a/.github/workflows/pre-deploy.yml
+++ b/.github/workflows/pre-deploy.yml
@@ -1,8 +1,8 @@
 name: Pre-build checks
 run-name: Preparing for deploy to GH Pages
-on: [push, pull_request] 
+on: [push, pull_request]
 permissions:
-    contents: write
+  contents: write
 
 jobs:
   Minify-Tailwind:
@@ -17,10 +17,8 @@ jobs:
           node-version: 18
       
       - name: Install dependencies
-        run: |
-          npm install -D tailwindcss
-          npm install -D eslint
-        
+        run: npm install -D tailwindcss
+      
       - name: Minify Tailwind CSS
         run: npx tailwindcss -i ./static/css/input.css -o ./static/css/index.css --minify
 
@@ -29,23 +27,49 @@ jobs:
           git config --global user.name "fer-hnndz"
           git config --global user.email "jfernandohernandez28@gmail.com"
           git add ./static/css/index.css
-          git commit -m "Minified tailwind"
-          git push
+          git commit -m "Minified tailwind" || echo "No changes to commit"
+          git push || echo "Push failed"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         continue-on-error: true
 
+  Lint-Javascript:
+    needs: Minify-Tailwind
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+          
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18
+        
+      - name: Install dependencies
+        run: npm install
+      
       - name: Lint Javascript
         run: npx eslint ./static/js/switchControl.js --no-config-lookup
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+  Deploy:
+    needs: Lint-Javascript
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Prepare artifact for upload
+        run: |
+          mkdir -p artifact
+          cp -r ./static ./artifact/
+          cp -r ./index.html ./artifact/
+    
       - name: Upload page artifact
         uses: actions/upload-pages-artifact@v1
         with:
           name: personal-website
-          path: /
-
+          path: artifact/
+    
       - name: Deploy to Github Pages
         uses: actions/deploy-pages@v1
         with:
